# Generated by Django 2.2.7 on 2019-12-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_zapatilla_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapatilla',
            name='imagen',
        ),
        migrations.AddField(
            model_name='zapatilla',
            name='foto_zapatilla',
            field=models.ImageField(blank=True, upload_to='foto_zapatilla'),
        ),
    ]
